// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp797qnrN8RAfgHeRd7LpXR8aSQsfSfH8',
    appId: '1:862270109027:web:febbb83128d1cef2bd0f56',
    messagingSenderId: '862270109027',
    projectId: 'examendi-177d6',
    authDomain: 'examendi-177d6.firebaseapp.com',
    storageBucket: 'examendi-177d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2OB7grRgci6sQq2dSgnUUwSY4qOTgzRU',
    appId: '1:862270109027:android:4f8191461b97ad11bd0f56',
    messagingSenderId: '862270109027',
    projectId: 'examendi-177d6',
    storageBucket: 'examendi-177d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlDBXQ7Xl1oqrs1-DGRxRmNDarER3yuG0',
    appId: '1:862270109027:ios:eb1de6bc484365ffbd0f56',
    messagingSenderId: '862270109027',
    projectId: 'examendi-177d6',
    storageBucket: 'examendi-177d6.appspot.com',
    iosClientId: '862270109027-do0a3bdlsu2vl31gcksebmm32b1ag44i.apps.googleusercontent.com',
    iosBundleId: 'com.example.albrox9.albabroxExamen2dam',
  );
}
